import catchErrors from '../utils/tryCatch';

const createAJob = catchErrors(async (req, res) => {});
const getAJob = catchErrors(async (req, res) => {});

export { createAJob, getAJob };
